Repository p0dalirius/smbclient-ng, pull requests merged in 2024-06, with the labels that each got.

#2 [bug] Missing requirement "rich"
  pyproject.toml
  requirements.txt
Labels: bug

#4 [bug] Prepend current directory to dir/ls argument
  smbclientng/core/SMBSession.py
Labels: bug

#14 [bug] Add default to domain variable to fix NoneType exception
  smbclientng/__main__.py
Labels: bug

#17 [enhancement] Implemented 'lrename' command, fixed #10
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
Labels: enhancement, new-command

#21 [enhancement] Added 'lcp' command, fixing #9
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
Labels: enhancement

#24 [enhancement] Add lcat lbat commands, fixing #22 #23
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
Labels: enhancement

#25 [enhancement] Add mount command
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
  smbclientng/core/SMBSession.py
Labels: enhancement

#29 [enhancement] Implement wildcards in 'get' command
  smbclientng/core/SMBSession.py
Labels: enhancement

#30 [enhancement] Prompt for password if one isn't included
  smbclientng/__main__.py
Labels: enhancement

#32 fix: add nargs for password arg to prompt if only -p is passed in
  smbclientng/__main__.py
Labels: waiting-for-response

#34 [bugfix] PWD stays the same when changing share
  smbclientng/__main__.py
  smbclientng/core/SMBSession.py
Labels: bug

#36 [enhancement] Implemented wildcards in get command, resolves #28
  smbclientng/core/CommandCompleter.py
  smbclientng/core/SMBSession.py
Labels: enhancement

#37 [enhancement] Implemented wildcards in pu command, resolves #35
  smbclientng/core/SMBSession.py
Labels: enhancement

#44 [enhancement] Implemented wildcards in 'rm' command, resolves #38
  documentation/search.js
  documentation/smbclientng/core/CommandCompleter.html
  documentation/smbclientng/core/InteractiveShell.html
  documentation/smbclientng/core/SMBSession.html
  smbclientng/core/InteractiveShell.py
  smbclientng/core/SMBSession.py
Labels: enhancement

#46 [bugfix] Fix missing backslash at the end of prompt fixes #45
  smbclientng/core/InteractiveShell.py
Labels: bug, enhancement

#47 [enhancement] Refactoring arguments parsing and implementing wildcards
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
  smbclientng/core/LocalFileIO.py
  smbclientng/core/SMBSession.py
  smbclientng/core/utils.py
Labels: enhancement

#49 [bugfix] Putting folder in remote subdirectory results in error and local file…
  smbclientng/core/SMBSession.py
Labels: bug

#54 [enhancement] Add option to read interactive commands from a file
  smbclientng/__main__.py
  smbclientng/core/Config.py
  smbclientng/core/InteractiveShell.py
Labels: enhancement

#53 [bugfix] CWD was added twice (in self.mkdir and in self.put_file_recursively
  smbclientng/core/SMBSession.py
Labels: bug

#55 [bugfix] Fixed variable config.startup_script
  smbclientng/core/InteractiveShell.py
Labels: bug

#57 [bugfix] Fixed double backslashes in paths printed by module find
  smbclientng/core/SMBSession.py
Labels: bug

#58 [enhancement] Add sessions manager
  smbclientng/__main__.py
  smbclientng/core/CommandCompleter.py
  smbclientng/core/Credentials.py
  smbclientng/core/InteractiveShell.py
  smbclientng/core/ModuleArgumentParser.py
  smbclientng/core/SMBSession.py
  smbclientng/core/SessionsManager.py
  smbclientng/core/utils.py
Labels: enhancement

#61 [enhancement] Add logger class
  smbclientng/__main__.py
  smbclientng/core/CommandCompleter.py
  smbclientng/core/InteractiveShell.py
  smbclientng/core/LocalFileIO.py
  smbclientng/core/Logger.py
  smbclientng/core/Module.py
  smbclientng/core/SMBSession.py
  smbclientng/core/SessionsManager.py
Labels: enhancement

#62 [enhancement] Add lines from startup script to history file, Fixes #59
  smbclientng/core/InteractiveShell.py
Labels: enhancement

#63 [bugfix] Using option -h on modules exits the command line, Fixes #60
  smbclientng/core/InteractiveShell.py
  smbclientng/core/Module.py
  smbclientng/core/ModuleArgumentParser.py
  smbclientng/core/SessionsManager.py
Labels: bug

#64 [bug] Various bugfixes
  smbclientng/core/InteractiveShell.py
  smbclientng/core/Logger.py
  smbclientng/core/SessionsManager.py
Labels: bug

#65 [enhancement] Improved output of SessionsManager commands
  smbclientng/core/SessionsManager.py
Labels: enhancement

#67 [enhancement] Refactored parts of CommandCompleter
  smbclientng/__main__.py
  smbclientng/core/CommandCompleter.py
Labels: enhancement

#68 [enhancement] Refactored parts of CommandCompleter
  smbclientng/core/CommandCompleter.py
Labels: enhancement

#70 [bugfix] Fixed cannot access local variable 'options' where it is not associated with a value
  smbclientng/core/SessionsManager.py
Labels: enhancement

#71 Release 2.0
  README.md
  documentation/search.js
  documentation/smbclientng/core.html
  documentation/smbclientng/core/CommandCompleter.html
  documentation/smbclientng/core/Config.html
  documentation/smbclientng/core/Credentials.html
  documentation/smbclientng/core/InteractiveShell.html
  documentation/smbclientng/core/LocalFileIO.html
  documentation/smbclientng/core/Logger.html
  documentation/smbclientng/core/Module.html
  documentation/smbclientng/core/ModuleArgumentParser.html
  documentation/smbclientng/core/SMBSession.html
  documentation/smbclientng/core/SessionsManager.html
  documentation/smbclientng/core/utils.html
  documentation/smbclientng/modules/Find.html
  documentation/smbclientng/modules/GPPPasswords.html
  pyproject.toml
  setup.py
  smbclientng/__main__.py
  smbclientng/core/CommandCompleter.py
Labels: enhancement

#72 [enhancement] Module users
  smbclientng/core/SMBSession.py
  smbclientng/modules/Find.py
  smbclientng/modules/GPPPasswords.py
  smbclientng/modules/Users.py
Labels: enhancement
